version: '3.3'
services:
  ngnix:
    build: ./nginx/
    restart: always
    volumes:
      - /home/zcherrad/data/nginx:/usr/share/nginx/html
    networks:
      - my_network
    ports:
      - 443:433

  mariadb:
    build: ./mariadb/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - /home/zcherrad/data/mariadb:/var/lib/mysql
    networks:
      - my_network

  wordpress:
    build: ./wordpress/
    restart: always
    volumes:
      - /home/zcherrad/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=mysecretpassword
      - WORDPRESS_DB_NAME=mywordpressdb
    networks:
      - my_network

networks:
  my_network:
