version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/tools:/etc/nginx/ssl/
      - wp-data:/var/www/
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/var/www/
    networks:
      - inception
    restart: always

volumes:
  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

  portainer-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/portainer

networks:
  inception:
    driver: bridge 

